In [170]:
import pandas as pd
import numpy as np

In [171]:
df = pd.read_csv("../eabl parsed csv/sales_products_merged_cleaned.csv")
df["quantity_cases"] = df["quantity"] * df["Cases_Conversion"]
df["returns_cases"] = df["return_quantity"] * df["Cases_Conversion"]
df

,source_file,salesperson,customer_code,cust_type,segment,visit_date,product,quantity,return_quantity,segment_grouped,...,FY25_July_NSV_Conversion_1st,FY25_November_NSV_Conversion_1st,FY25_January_NSV_Conversion_1st,FY26_October_NSV_Conversion_18th,FY25_EX_KBL_Price_Per_Case,FY26_October_NSV_Conversion_18th_Updated,FY26_June_NSV_Conversion_15th,FY26_EX_KBL_Price_Per_Case,quantity_cases,returns_cases
0,DailySalesReportNew_0101202615012026.xlsx,JOHN MWANGI-CBD,KE0062192,Cash,Bar,2026-01-08,Euroform Amber Local 500ml,7.00,7,Bar,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,7.000,7.0
1,DailySalesReportNew_0101202615012026.xlsx,JOHN MWANGI-CBD,KE0062192,Cash,Bar,2026-01-08,Tusker Lager 500ml Per Bottle,0.28,0,Bar,...,1687.169954,1687.169954,2286.444954,2286.444954,4045.697200,2286.444954,2286.444954,3933.747412,0.280,0.0
2,DailySalesReportNew_0101202615012026.xlsx,JOHN MWANGI-CBD,KE0062192,Cash,Bar,2026-01-08,Kenya Cane Lemon & Ginger 25cl 40X01,1.00,0,Bar,...,1.000000,97.775000,109.860836,109.860836,9739.298206,134.860836,134.860836,9737.542792,0.025,0.0
3,DailySalesReportNew_0101202615012026.xlsx,JOHN MWANGI-CBD,KE0062192,Cash,Bar,2026-01-08,Smrnf Red 25Cl 40X01 Reggie,2.00,0,Bar,...,251.917884,251.917884,247.273859,247.273859,15825.727060,247.273859,247.273859,15823.507037,0.050,0.0
4,DailySalesReportNew_0101202615012026.xlsx,JOHN MWANGI-CBD,KE0062192,Cash,Bar,2026-01-08,Guinness (K) Per Bottle,0.60,0,Bar,...,2397.221778,2397.221778,2349.621778,2349.621778,4869.355200,2349.621778,2349.621778,4846.186262,0.600,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984287,DailySalesReportNew_1606202630062026.xlsx,JOEL MAINA MWAURA-UDV VAN,KE0170375,Cash,Specialist Store,2026-06-27,Smirnoff Ice Raspberry Twist 300ml in Bottle,0.32,0,Specialist Store,...,1.000000,1.000000,1.000000,1.000000,3734.000000,2732.000000,2732.000000,3734.000000,0.320,0.0
984288,DailySalesReportNew_1606202630062026.xlsx,JOEL MAINA MWAURA-UDV VAN,KE0187045,Cash,Bar,2026-06-17,Smirnoff Ice Raspberry Twist 300ml in Bottle,0.60,0,Bar,...,1.000000,1.000000,1.000000,1.000000,3734.000000,2732.000000,2732.000000,3734.000000,0.600,0.0
984289,DailySalesReportNew_1606202630062026.xlsx,JOSEPH MWANIKI-KANU,KE0071094,Credit,Specialist Store,2026-06-30,Smirnoff Ice Raspberry Twist 300ml in Bottle,1.00,0,Specialist Store,...,1.000000,1.000000,1.000000,1.000000,3734.000000,2732.000000,2732.000000,3734.000000,1.000,0.0
984290,DailySalesReportNew_1606202630062026.xlsx,SEBASTIAN MUKHANZI-GILGIL,KE0167300,Cash,Restaurant,2026-06-20,Smirnoff Ice Raspberry Twist 300ml in Bottle,0.48,0,Other,...,1.000000,1.000000,1.000000,1.000000,3734.000000,2732.000000,2732.000000,3734.000000,0.480,0.0
984291,DailySalesReportNew_1606202630062026.xlsx,SEBASTIAN MUKHANZI-GILGIL,KE0188685,Cash,Bar,2026-06-24,Smirnoff Ice Raspberry Twist 300ml in Bottle,0.24,0,Bar,...,1.000000,1.000000,1.000000,1.000000,3734.000000,2732.000000,2732.000000,3734.000000,0.240,0.0

In [172]:
# Just the column names
print(list(df.columns))

['source_file', 'salesperson', 'customer_code', 'cust_type', 'segment', 'visit_date', 'product', 'quantity', 'return_quantity', 'segment_grouped', 'Product_Code', 'Product_Description', 'Handheld_Description', 'Status', 'Default_UOM', 'Category', 'Sub_Category', 'New_Sub_Category2', 'Brand', 'SKU', 'Pack_Format', 'Bottles_Per_Case', 'Pack_Size_mls', 'Cases_Conversion', 'EU_Conversion', 'Battleground_Category', 'Sub_Category1', 'CATMAN_Category', 'FY25_July_NSV_Conversion_1st', 'FY25_November_NSV_Conversion_1st', 'FY25_January_NSV_Conversion_1st', 'FY26_October_NSV_Conversion_18th', 'FY25_EX_KBL_Price_Per_Case', 'FY26_October_NSV_Conversion_18th_Updated', 'FY26_June_NSV_Conversion_15th', 'FY26_EX_KBL_Price_Per_Case', 'quantity_cases', 'returns_cases']

In [173]:
# Column names + data types + non-null counts
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984292 entries, 0 to 984291
Data columns (total 38 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   source_file                               984292 non-null  object
 1   salesperson                               984292 non-null  object
 2   customer_code                             984292 non-null  object
 3   cust_type                                 984292 non-null  object
 4   segment                                   984292 non-null  object
 5   visit_date                                984292 non-null  object
 6   product                                   984292 non-null  object
 7   quantity                                  984292 non-null  float64
 8   return_quantity                           984292 non-null  int64
 9   segment_grouped                           984292 non-null  object
 10  Product_Code                              984292 non-null  object
 11  Product_Description                       984292 non-null  object
 12  Handheld_Description                      984292 non-null  object
 13  Status                                    984292 non-null  object
 14  Default_UOM                               984292 non-null  object
 15  Category                                  984292 non-null  object
 16  Sub_Category                              984292 non-null  object
 17  New_Sub_Category2                         984292 non-null  object
 18  Brand                                     984292 non-null  object
 19  SKU                                       984292 non-null  object
 20  Pack_Format                               984292 non-null  object
 21  Bottles_Per_Case                          984292 non-null  float64
 22  Pack_Size_mls                             984292 non-null  float64
 23  Cases_Conversion                          984292 non-null  float64
 24  EU_Conversion                             984292 non-null  float64
 25  Battleground_Category                     984292 non-null  object
 26  Sub_Category1                             984292 non-null  object
 27  CATMAN_Category                           984292 non-null  object
 28  FY25_July_NSV_Conversion_1st              984292 non-null  float64
 29  FY25_November_NSV_Conversion_1st          984292 non-null  float64
 30  FY25_January_NSV_Conversion_1st           984292 non-null  float64
 31  FY26_October_NSV_Conversion_18th          984292 non-null  float64
 32  FY25_EX_KBL_Price_Per_Case                984292 non-null  float64
 33  FY26_October_NSV_Conversion_18th_Updated  984292 non-null  float64
 34  FY26_June_NSV_Conversion_15th             984292 non-null  float64
 35  FY26_EX_KBL_Price_Per_Case                984292 non-null  float64
 36  quantity_cases                            984292 non-null  float64
 37  returns_cases                             984292 non-null  float64
dtypes: float64(15), int64(1), object(22)
memory usage: 285.4+ MB
None

In [174]:
# Column names + data types, null counts, and unique value counts together
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "non_null": df.notna().sum(),
    "nulls": df.isna().sum(),
    "unique_values": df.nunique()
})
print(summary)

                                            dtype  non_null  nulls  \
source_file                                object    984292      0
salesperson                                object    984292      0
customer_code                              object    984292      0
cust_type                                  object    984292      0
segment                                    object    984292      0
visit_date                                 object    984292      0
product                                    object    984292      0
quantity                                  float64    984292      0
return_quantity                             int64    984292      0
segment_grouped                            object    984292      0
Product_Code                               object    984292      0
Product_Description                        object    984292      0
Handheld_Description                       object    984292      0
Status                                     object    984292      0
Default_UOM                                object    984292      0
Category                                   object    984292      0
Sub_Category                               object    984292      0
New_Sub_Category2                          object    984292      0
Brand                                      object    984292      0
SKU                                        object    984292      0
Pack_Format                                object    984292      0
Bottles_Per_Case                          float64    984292      0
Pack_Size_mls                             float64    984292      0
Cases_Conversion                          float64    984292      0
EU_Conversion                             float64    984292      0
Battleground_Category                      object    984292      0
Sub_Category1                              object    984292      0
CATMAN_Category                            object    984292      0
FY25_July_NSV_Conversion_1st              float64    984292      0
FY25_November_NSV_Conversion_1st          float64    984292      0
FY25_January_NSV_Conversion_1st           float64    984292      0
FY26_October_NSV_Conversion_18th          float64    984292      0
FY25_EX_KBL_Price_Per_Case                float64    984292      0
FY26_October_NSV_Conversion_18th_Updated  float64    984292      0
FY26_June_NSV_Conversion_15th             float64    984292      0
FY26_EX_KBL_Price_Per_Case                float64    984292      0
quantity_cases                            float64    984292      0
returns_cases                             float64    984292      0

                                          unique_values
source_file                                          31
salesperson                                          23
customer_code                                       948
cust_type                                             2
segment                                              12
visit_date                                          399
product                                             223
quantity                                            436
return_quantity                                     144
segment_grouped                                       7
Product_Code                                        222
Product_Description                                 222
Handheld_Description                                221
Status                                                2
Default_UOM                                           4
Category                                              3
Sub_Category                                          7
New_Sub_Category2                                    10
Brand                                                84
SKU                                                 185
Pack_Format                                           6
Bottles_Per_Case                                      8
Pack_Size_mls                                        12
Cases_Conversion                                      8
EU_Conversion                                        17
Battleground_Category                                12
Sub_Category1                                        22
CATMAN_Category                                      14
FY25_July_NSV_Conversion_1st                        108
FY25_November_NSV_Conversion_1st                    115
FY25_January_NSV_Conversion_1st                     138
FY26_October_NSV_Conversion_18th                    141
FY25_EX_KBL_Price_Per_Case                          165
FY26_October_NSV_Conversion_18th_Updated            148
FY26_June_NSV_Conversion_15th                       149
FY26_EX_KBL_Price_Per_Case                          132
quantity_cases                                      742
returns_cases                                       144

In [175]:
# Are they identical everywhere?
are_identical = (df["segment"] == df["segment_grouped"]).all()
print("Identical in every row?", are_identical)

# How many rows differ?
diff_count = (df["segment"] != df["segment_grouped"]).sum()
print("Rows where they differ:", diff_count)
print("Rows where they match:", len(df) - diff_count)

# See what the differences actually look like
diff_rows = df[df["segment"] != df["segment_grouped"]][["segment", "segment_grouped"]].drop_duplicates()
print(diff_rows)

Identical in every row? False
Rows where they differ: 24562
Rows where they match: 959730
               segment segment_grouped
243         Restaurant           Other
2588       Supermarket           Other
2598        Recreation           Other
3499       Marketplace           Other
21357      Convenience           Other
686663  Not Applicable           Other

### What is the finest level of detail your data is captured at, and is that level actually usable for building a model — or is it too sparse/noisy to model directly?

### Is there a trend in a specific customer purchasing eg Tusker in terms of quantity in different days of the week so that we can forecast what they are likely to but when they show up.

#### How many times a combination of "customer_code", "Product_Code", "visit_date" shows up

In [176]:
df["visit_date"] = pd.to_datetime(df["visit_date"])
grp = df.groupby(["customer_code", "Product_Code", "visit_date"]).size()
grp

customer_code  Product_Code  visit_date
KE0026250      350197        2026-06-12    1
               350199        2025-04-18    1
                             2025-08-22    1
                             2025-10-03    1
                             2025-10-21    1
                                          ..
KE0200308      795393        2026-06-26    1
                             2026-06-27    1
                             2026-06-29    1
                             2026-06-30    1
               B616861       2026-06-29    1
Length: 955500, dtype: int64

#### Counts how many buckets exist in total (i.e., how many distinct customer+product+day combinations show up at all).

In [177]:
n_total = len(grp)
n_total

955500

In [178]:
#Counts how many buckets exist in total (i.e., how many distinct customer+product+day combinations show up at all).
pct_singleton = (grp == 1).mean() * 100
print(n_total, pct_singleton)

955500 97.2959706959707

### Fixing of the CustomerMaster.xlsx dataset by removing useless Columns

In [179]:
cm = pd.read_excel("../EABL dataset/CustomerMaster_cleanV1.xlsx")

cm

,Distributor Code,Mode of Payment,DMS Customer Code,Customer Name,Cust Status,Price Group,global Channel,Sub-Channel,Segment,Sub-Segment 1,...,price_group_missing,rss_date_filled,rss_date_unresolved,registration_batch,ever_logged_in,login_status,days_since_last_login,gps_missing,gps_address_matched,gps_unresolved
0,298703,Cash,KE0162873,GROUNDLESS LOUNGE,INACTIVE,UP01 - Upstream Retail Price List,001 - On Trade,034 - On Trade,123 - Nightclub,009 - Modern Nightclub,...,False,False,False,Batch_084_2022-11-22,True,Logged In,835.0,False,False,False
1,298703,Cash,KE0162875,CONTAINER WINES,ACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,False,False,False,Batch_084_2022-11-22,True,Logged In,281.0,False,False,False
2,298703,Cash,KE0162877,BRUNO'S WINES,INACTIVE,UP01 - Upstream Retail Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,False,False,False,Batch_084_2022-11-22,True,Logged In,1261.0,False,False,False
3,298703,Cash,KE0162878,SURF AND SAND WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,False,False,False,Batch_084_2022-11-22,True,Logged In,405.0,False,False,False
4,298703,Cash,KE0162879,INFINITY WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,False,False,False,Batch_084_2022-11-22,True,Logged In,743.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2232,298703,Cash,KE0162646,"New Yako, Nakuru",ACTIVE,UP_S000007 - REBATE PRICE GROUP T1,008 - Route to Market,031 - Wholesaler,119 - Wholesaler,004 - Modern Wholesaler,...,False,False,False,Batch_082_2022-11-18,True,Logged In,3.0,False,False,False
2233,298703,Cash,KE0162755,SUPREME WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,False,False,False,Batch_083_2022-11-20,False,Registered — Never Logged In,NaN,False,False,False
2234,298703,Cash,KE0162756,BUBBLE WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,False,False,False,Batch_083_2022-11-20,False,Registered — Never Logged In,NaN,False,False,False
2235,298703,Cash,KE0162757,"WEST WOOD,NGANO",ACTIVE,UP01 - Upstream Retail Price List,001 - On Trade,034 - On Trade,122 - Bar,007 - Traditional Bar,...,False,False,False,Batch_083_2022-11-20,True,Logged In,3.0,False,False,False
2236,298703,Cash,KE0162758,"CLUB VEGAS,GWA KIONGO",INACTIVE,UP01 - Upstream Retail Price List,001 - On Trade,034 - On Trade,122 - Bar,007 - Traditional Bar,...,False,False,False,Batch_083_2022-11-20,False,Registered — Never Logged In,NaN,False,False,False

In [180]:
columns_to_drop = [
    "days_since_last_login",
    "GPS Co-ordinate",
    "RSS Last Login Date",
    "RSS Date Registed",
    "RSS First Login Date",
]

# errors="ignore" means it won't crash if a name doesn't match exactly
cm_trimmed = cm.drop(columns=columns_to_drop, errors="ignore")

# Save to a NEW file — CustomerMaster.xlsx itself is never touched
cm_trimmed.to_excel("../EABL dataset/CustomerMaster_cleanV2.xlsx", index=False)

print("Original columns:", len(cm.columns))
print("Trimmed columns:", len(cm_trimmed.columns))
print(list(cm_trimmed.columns))
cm_trimmed

Original columns: 47
Trimmed columns: 42
['Distributor Code', 'Mode of Payment', 'DMS Customer Code', 'Customer Name', 'Cust Status', 'Price Group', 'global Channel', 'Sub-Channel', 'Segment', 'Sub-Segment 1', 'Sub-Segment 2', 'Sub-Segment 3', 'Sub-Segment 4', 'Volume Grade', 'Archi Type', 'OBOS', 'Division', 'Area', 'Territory', 'Route', 'Address', 'Contact Detail', 'Outstanding Balance', 'Approval Status', 'Open Account Date', 'Cutsomer Type', 'RSS Flag', 'MPA Type', 'Last updated date-time', 'Terms and Conditions Policy', 'Privacy Policy', 'Cookies Policy', 'has_alternate_name', 'price_group_missing', 'rss_date_filled', 'rss_date_unresolved', 'registration_batch', 'ever_logged_in', 'login_status', 'gps_missing', 'gps_address_matched', 'gps_unresolved']

,Distributor Code,Mode of Payment,DMS Customer Code,Customer Name,Cust Status,Price Group,global Channel,Sub-Channel,Segment,Sub-Segment 1,...,has_alternate_name,price_group_missing,rss_date_filled,rss_date_unresolved,registration_batch,ever_logged_in,login_status,gps_missing,gps_address_matched,gps_unresolved
0,298703,Cash,KE0162873,GROUNDLESS LOUNGE,INACTIVE,UP01 - Upstream Retail Price List,001 - On Trade,034 - On Trade,123 - Nightclub,009 - Modern Nightclub,...,True,False,False,False,Batch_084_2022-11-22,True,Logged In,False,False,False
1,298703,Cash,KE0162875,CONTAINER WINES,ACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,True,False,False,False,Batch_084_2022-11-22,True,Logged In,False,False,False
2,298703,Cash,KE0162877,BRUNO'S WINES,INACTIVE,UP01 - Upstream Retail Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,True,False,False,False,Batch_084_2022-11-22,True,Logged In,False,False,False
3,298703,Cash,KE0162878,SURF AND SAND WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,True,False,False,False,Batch_084_2022-11-22,True,Logged In,False,False,False
4,298703,Cash,KE0162879,INFINITY WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,True,False,False,False,Batch_084_2022-11-22,True,Logged In,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2232,298703,Cash,KE0162646,"New Yako, Nakuru",ACTIVE,UP_S000007 - REBATE PRICE GROUP T1,008 - Route to Market,031 - Wholesaler,119 - Wholesaler,004 - Modern Wholesaler,...,False,False,False,False,Batch_082_2022-11-18,True,Logged In,False,False,False
2233,298703,Cash,KE0162755,SUPREME WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,True,False,False,False,Batch_083_2022-11-20,False,Registered — Never Logged In,False,False,False
2234,298703,Cash,KE0162756,BUBBLE WINES,INACTIVE,UP02 - Upstream Stockiest Price List,002 - Off Trade,035 - Retailer,134 - Specialist Store,032 - Traditional Specialist Store,...,True,False,False,False,Batch_083_2022-11-20,False,Registered — Never Logged In,False,False,False
2235,298703,Cash,KE0162757,"WEST WOOD,NGANO",ACTIVE,UP01 - Upstream Retail Price List,001 - On Trade,034 - On Trade,122 - Bar,007 - Traditional Bar,...,True,False,False,False,Batch_083_2022-11-20,True,Logged In,False,False,False
2236,298703,Cash,KE0162758,"CLUB VEGAS,GWA KIONGO",INACTIVE,UP01 - Upstream Retail Price List,001 - On Trade,034 - On Trade,122 - Bar,007 - Traditional Bar,...,True,False,False,False,Batch_083_2022-11-20,False,Registered — Never Logged In,False,False,False

In [181]:
cm_trimmed.isna().sum()

Distributor Code               0
Mode of Payment                0
DMS Customer Code              0
Customer Name                  0
Cust Status                    0
Price Group                    0
global Channel                 0
Sub-Channel                    0
Segment                        0
Sub-Segment 1                  0
Sub-Segment 2                  0
Sub-Segment 3                  0
Sub-Segment 4                  0
Volume Grade                   0
Archi Type                     0
OBOS                           0
Division                       0
Area                           0
Territory                      0
Route                          0
Address                        0
Contact Detail                 0
Outstanding Balance            0
Approval Status                0
Open Account Date              0
Cutsomer Type                  0
RSS Flag                       0
MPA Type                       0
Last updated date-time         0
Terms and Conditions Policy    0
Privacy Policy                 0
Cookies Policy                 0
has_alternate_name             0
price_group_missing            0
rss_date_filled                0
rss_date_unresolved            0
registration_batch             0
ever_logged_in                 0
login_status                   0
gps_missing                    0
gps_address_matched            0
gps_unresolved                 0
dtype: int64

### "Does my data actually have layers/Hierachy — like a family tree — or is everything just at one flat level pretending to have layers?"

In [182]:
pm = pd.read_csv("../eabl parsed csv/product_master_cleaned.csv")     # columns: Category2, Brand, Product_Code

for c in ["Category2", "Brand"]:
#how many different Categories exist
#how many different Brands exist
    print(c, pm[c].nunique())
print("SKU", pm["Product_Code"].nunique())
for c in ["Division", "Area", "Territory", "Route"]:
    print(c, cm_trimmed[c].nunique())

Category2 6
Brand 138
SKU 881
Division 4
Area 6
Territory 11
Route 13

In [ ]:
fact = pd.read_csv("fact_table.csv")                          # columns: Brand
pm = pd.read_csv("product_master_cleaned.csv")                # columns: Category, Category2
merged = pd.read_csv("sales_products_merged_cleaned.csv")     # columns: segment, segment_grouped

pct_unmatched = fact["Brand"].isna().mean() * 100
pct_cat_diff = (pm["Category"] != pm["Category2"]).mean() * 100
pct_seg_diff = (merged["segment"] != merged["segment_grouped"]).mean() * 100
print(pct_unmatched, pct_cat_diff, pct_seg_diff)

In [183]:
# Columns we agreed are not needed for forecasting
columns_to_drop = [
    "source_file",
    "salesperson",
    "cust_type",
    "Product_Description",
    "Handheld_Description",
    "Default_UOM",
    "Pack_Format",
    "Bottles_Per_Case",
    "Pack_Size_mls",
    'FY25_July_NSV_Conversion_1st', 
    'FY25_November_NSV_Conversion_1st', 
    'FY25_January_NSV_Conversion_1st', 
    'FY26_October_NSV_Conversion_18th', 
    'FY25_EX_KBL_Price_Per_Case', 
    'FY26_October_NSV_Conversion_18th_Updated', 
    'FY26_June_NSV_Conversion_15th', 'FY26_EX_KBL_Price_Per_Case'
]

# drop() with a new variable name leaves 'df' (and the original CSV) untouched
df_trimmed = df.drop(columns=columns_to_drop)

# Save to a NEW file — original sales_products_merged_cleaned.csv is never overwritten
df_trimmed.to_csv("sales_products_forecast_ready.csv", index=False)

print("Original columns:", len(df.columns))
print("Trimmed columns:", len(df_trimmed.columns))
print(list(df_trimmed.columns))

Original columns: 38
Trimmed columns: 21
['customer_code', 'segment', 'visit_date', 'product', 'quantity', 'return_quantity', 'segment_grouped', 'Product_Code', 'Status', 'Category', 'Sub_Category', 'New_Sub_Category2', 'Brand', 'SKU', 'Cases_Conversion', 'EU_Conversion', 'Battleground_Category', 'Sub_Category1', 'CATMAN_Category', 'quantity_cases', 'returns_cases']